-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 20:59:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema funko_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema funko_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `funko_db` DEFAULT CHARACTER SET utf8 ;
USE `funko_db` ;

-- -----------------------------------------------------
-- Table `funko_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_db`.`category` (
    `category_id` INT NOT NULL AUTO_INCREMENT,
    `category_name` VARCHAR(100) NOT NULL,
    `category_description` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`category_id`)
)  ENGINE=INNODB COMMENT='		';


-- -----------------------------------------------------
-- Table `funko_db`.`license`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_db`.`license` (
    `license_id` INT NOT NULL AUTO_INCREMENT,
    `license_name` VARCHAR(45) NOT NULL,
    `license_description` VARCHAR(255) NOT NULL,
    `license_image` VARCHAR(255) NOT NULL,
    `licensecol` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`license_id`)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `funko_db`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_db`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(60) NOT NULL,
  `product_description` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `discount` INT NOT NULL,
  `sku` VARCHAR(30) NOT NULL,
  `dues` INT NOT NULL,
  `image_front` VARCHAR(200) NOT NULL,
  `image_back` VARCHAR(200) NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `license_id` INT NOT NULL,
  `categori_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `license_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_category_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_product_license1_idx` (`license_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `funko_db`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_license1`
    FOREIGN KEY (`license_id`)
    REFERENCES `funko_db`.`license` (`license_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `funko_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_db`.`user` (
    `user_id` INT NOT NULL AUTO_INCREMENT,
    `lastname` VARCHAR(80) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `passwowrd` VARCHAR(32) NOT NULL,
    `create_time` TIMESTAMP NOT NULL,
    `usercol` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`user_id`)
)  ENGINE=INNODB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

